[mongodb]
mongodb.dileep.sbs 
[catalogue]
catalogue.dileep.sbs
[user]
user.dileep.sbs 
[cart]
cart.dileep.sbs 
[web]
web.dileep.sbs 
[redis]
redis.dileep.sbs 
[mysql]
mysql.dileep.sbs 
[shipping]
shipping.dileep.sbs 
[rabbitmq]
rabbitmq.dileep.sbs 
payment.dileep.sbs 
[dispatch]
dispatch.dileep.sbs 
[localhost]
localhost 

 [all:vars]
 ansible_password=DevOps321