MONGODB_HOST: mongodb.dileep.sbs  # submit your host
REDIS_HOST: redis-dev.dileep.sbs 
MYSQL_HOST: mysql-dev.dileep.sbs 
RABBITMQ_HOST: rabbitmq-dev.dileep.sbs 
CATALOGUE_HOST: catalogue-dev.dileep.sbs 
USER_HOST: user-dev.dileep.sbs 
CART_HOST: cart-dev.dileep.sbs 
SHIPPING_HOST: shipping-dev.dileep.sbs 
PAYMENT_HOST: payment-dev.dileep.sbs 
DISPATCH_HOST: dispatch-dev.dileep.sbs 